spring.application.name=order-service-17
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.openfeign.circuitbreaker.enabled=true
feign.circuitbreaker.enabled=true